Bac 1191 two new sdk function
etherspot/etherspot-sdk pull request #106
Opened 2022-03-07 13:57 UTC by riccardopillar

2022-03-07 14:45 UTC, rafaelcidade commented on src/sdk/sdk.ts
> +    const numberOfTokens = utils.parseUnits(value, 18)
Token decimals should not be hardcoded

2022-03-07 14:46 UTC, rafaelcidade commented on src/sdk/sdk.ts
> +    const account = this.state.accountAddress;
`this.state.p2pPaymentDepositAddress`

2022-03-07 14:46 UTC, rafaelcidade commented on src/sdk/sdk.ts
> +    const account = this.state.p2pPaymentDepositAddress;
`this.state.accountAddress`

2022-03-07 14:46 UTC, zincoshine requested changes

2022-03-07 14:46 UTC, zincoshine commented on .gitignore
> +workspace.code-workspace
Pls don't push workspace to the repo.

2022-03-07 14:46 UTC, zincoshine commented on .gitignore
> +workspace.code-workspace
Ah wait this is to .gitignore, then I guess that's alright.

2022-03-07 14:46 UTC, zincoshine commented on src/sdk/sdk.ts
> +    const account = this.state.p2pPaymentDepositAddress;
This must be the accountAddress

2022-03-07 14:46 UTC, zincoshine commented on src/sdk/sdk.ts
> +    const account = this.state.accountAddress;
This has to be the P2P address.

2022-03-07 14:46 UTC, zincoshine commented on src/sdk/sdk.ts
> +        // console.dir(transferResult)
Please remove unused code. Should we replace it with a proper return message?

2022-03-07 14:46 UTC, zincoshine commented on src/sdk/sdk.ts
> +    const wallet: Partial<Wallet> = this.services.walletService.walletProvider;
How are we handling null here? What if walletProvider is null? Please add appropriate try/catch

2022-03-07 14:46 UTC, zincoshine commented on workspace.code-workspace
> +{
This file has to be deleted from the PR

2022-03-07 18:30 UTC, zincoshine requested changes

2022-03-07 18:30 UTC, zincoshine commented on src/sdk/account/account.service.ts
> +  isAccountTypeContract():boolean {
I would rename the function as isContractAccount()

2022-03-07 19:01 UTC, SaltyCucumber commented on src/sdk/sdk.ts
> +  ];
maybe getContractAbi can help, look it up in the sdk code

2022-03-08 09:44 UTC, riccardopillar commented on src/sdk/sdk.ts
> +  private async transferTokens(account: string, value: string, contractAddress: string, decimals = 18): Promise<void> {
I guess is more safe remove the default value

2022-03-08 09:48 UTC, riccardopillar commented on src/sdk/sdk.ts
> +    if (this.services.accountService.isContractAccount()) await this.computeContractAccount({
actually the condition should be if not, was an error from my side

2022-03-08 09:52 UTC, rafaelcidade approved these changes

2022-03-08 09:54 UTC, zincoshine approved these changes

2022-03-08 09:59 UTC, SaltyCucumber approved these changes

2022-03-08 10:31 UTC, riccardopillar commented on .gitignore
> +workspace.code-workspace
I have added it for avoid to commit the file

2022-03-08 14:56 UTC, riccardopillar commented on examples/src/03-contract-account.ts
> +
I have run it, it seems it doesn't

2022-03-09 11:05 UTC, merged