Pro 147 lifi sdk2
etherspot/etherspot-sdk pull request #130
Opened 2022-06-09 17:51 UTC by riccardopillar

2022-06-14 08:56 UTC, vignesha22 commented on src/sdk/network/utils/network-name-to-chain-id.ts
> +  console.log(networkName);
Can you remove logs pls

2022-06-14 20:58 UTC, zincoshine requested changes
Remove console.logs and pls follow the same indent mechanism as the repo

2022-06-15 09:51 UTC, zincoshine requested changes

2022-06-15 09:51 UTC, zincoshine commented on examples/.env.dev
> +MATIC_PRIVATE_KEY=
Why do we need these? Please remove them.

2022-06-15 10:02 UTC, zincoshine approved these changes

2022-06-15 11:48 UTC, merged